name: Backend Actions

on: [push]

permissions:
  contents: write

jobs:
  deploy:
    name: deploy
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      super_secret: ${{ secrets.SANITY_AUTH_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install & Deploy
        run: |
          yarn install
          yarn build
          yarn deploy --yes
        working-directory: backend
